pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat './Jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                bat './Jenkins/scripts/deliver.sh'
                bat './Jenkins/scripts/kill.sh'
            }
        }
    }
}
